// lib/models/shop_data.dart

// ショップに並べるアイテムのデータ構造を定義
class ShopItem {
  final String name;
  final String imagePath;
  final int price;
  final String type; // 'clothes' or 'house'
  final int requiredLevel;
  final bool isIslandOnly;
  final bool isSeaOnly;
  final bool isSkyOnly;
  final bool isSpaceOnly;

  ShopItem({
    required this.name,
    required this.imagePath,
    required this.price,
    required this.type,
    this.requiredLevel = 1,
    this.isIslandOnly = false,
    this.isSeaOnly = false,
    this.isSkyOnly = false,
    this.isSpaceOnly = false,
  });
}

// ショップのカタログデータ
final List<ShopItem> shopItems = [
  ShopItem(
    name: 'あおいふく',
    imagePath: 'assets/images/clothes/clothes_blue.png',
    price: 50,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'あかいふく',
    imagePath: 'assets/images/clothes/clothes_red.png',
    price: 50,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'みどりのふく',
    imagePath: 'assets/images/clothes/clothes_green.png',
    price: 50,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ふつうのおうち',
    imagePath: 'assets/images/house_normal.png',
    price: 500,
    type: 'house',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'りっぱなおうち',
    imagePath: 'assets/images/house_rich.png',
    price: 1500,
    type: 'house',
    requiredLevel: 1,
  ),
  // 必要であれば、ここにデフォルトの服と家も追加しておくと便利です
  ShopItem(
    name: 'いつものふく',
    imagePath: 'assets/images/clothes/clothes_default.png',
    price: 0,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'おとこのこ',
    imagePath: 'assets/images/clothes/clothes_boy_default.png',
    price: 0,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'さいしょのおうち',
    imagePath: 'assets/images/house.png',
    price: 0,
    type: 'house',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'みどりのふく（おとこのこ）',
    imagePath: 'assets/images/clothes/clothes_boy_green.png',
    price: 50,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'あかいふく（おとこのこ）',
    imagePath: 'assets/images/clothes/clothes_boy_red.png',
    price: 50,
    type: 'clothes',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'あかのドレス',
    imagePath: 'assets/images/clothes/clothes_dress_red.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'あおのドレス',
    imagePath: 'assets/images/clothes/clothes_dress_blue.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ピンクドレス',
    imagePath: 'assets/images/clothes/clothes_dress_pink.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'くま',
    imagePath: 'assets/images/clothes/clothes_kuma.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'きょうりゅう',
    imagePath: 'assets/images/clothes/clothes_kyoryu.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おうじさま',
    imagePath: 'assets/images/clothes/clothes_boy_oujisama.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ぼうけんしゃ',
    imagePath: 'assets/images/clothes/clothes_boy_boukensya.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ヒーロー',
    imagePath: 'assets/images/clothes/clothes_boy_hiro.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'カウボーイ',
    imagePath: 'assets/images/clothes/clothes_boy_kauboy.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'せんし',
    imagePath: 'assets/images/clothes/clothes_boy_senshi.png',
    price: 200,
    type: 'clothes',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'アロハシャツ（海）',
    imagePath: 'assets/images/clothes/clothes_sea_aroha.png',
    price: 300,
    type: 'clothes',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'にんぎょ（海）',
    imagePath: 'assets/images/clothes/clothes_sea_ningyo.png',
    price: 300,
    type: 'clothes',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'すいへい（海）',
    imagePath: 'assets/images/clothes/clothes_sea_suihei.png',
    price: 300,
    type: 'clothes',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'せんすいちょう（海）',
    imagePath: 'assets/images/clothes/clothes_sea_sensuityo.png',
    price: 300,
    type: 'clothes',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'かいぞく（海）',
    imagePath: 'assets/images/clothes/clothes_sea_kaizoku.png',
    price: 300,
    type: 'clothes',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ウサギ',
    imagePath: 'assets/images/character_usagi.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ネコ',
    imagePath: 'assets/images/character_neko.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'キリン',
    imagePath: 'assets/images/character_kirin.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ゾウ',
    imagePath: 'assets/images/character_zou.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'クマ',
    imagePath: 'assets/images/character_kuma.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'パンダ',
    imagePath: 'assets/images/character_panda.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'サル',
    imagePath: 'assets/images/character_saru.gif',
    price: 300,
    type: 'character',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'おんなのこ',
    imagePath: 'assets/images/character_girl.gif',
    price: 450,
    type: 'character',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おひめさま',
    imagePath: 'assets/images/character_hime.gif',
    price: 450,
    type: 'character',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おうじさま（おうえん）',
    imagePath: 'assets/images/character_ouji.gif',
    price: 450,
    type: 'character',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'きょうりゅう（おうえん）',
    imagePath: 'assets/images/character_kyoryu.gif',
    price: 450,
    type: 'character',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ロボット',
    imagePath: 'assets/images/character_robo.gif',
    price: 450,
    type: 'character',
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'イルカ（海）',
    imagePath: 'assets/images/character_sea_iruka.gif',
    price: 600,
    type: 'character',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'カメ（海）',
    imagePath: 'assets/images/character_sea_kame.gif',
    price: 600,
    type: 'character',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'さかな（海）',
    imagePath: 'assets/images/character_sea_sakana.gif',
    price: 600,
    type: 'character',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'シャチ（海）',
    imagePath: 'assets/images/character_sea_syachi.gif',
    price: 600,
    type: 'character',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'はな１',
    imagePath: 'assets/images/item_hana1.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'はな２',
    imagePath: 'assets/images/item_hana2.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'はっぱ１',
    imagePath: 'assets/images/item_happa1.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'はっぱ２',
    imagePath: 'assets/images/item_happa2.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'はちうえ',
    imagePath: 'assets/images/item_hatiue.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'くさ1',
    imagePath: 'assets/images/item_kusa1.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'くさ2',
    imagePath: 'assets/images/item_kusa2.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'き',
    imagePath: 'assets/images/item_ki.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'じょうろ',
    imagePath: 'assets/images/item_jouro.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'コイン',
    imagePath: 'assets/images/item_koin.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'たからばこ',
    imagePath: 'assets/images/item_takarabako.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ボール',
    imagePath: 'assets/images/item_bo-ru.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'たいよう',
    imagePath: 'assets/images/item_taiyou.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'つき',
    imagePath: 'assets/images/item_tsuki.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ほし',
    imagePath: 'assets/images/item_hoshi.png',
    price: 50,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'じてんしゃ',
    imagePath: 'assets/images/item_jitensya.png',
    price: 100,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'くるま',
    imagePath: 'assets/images/item_kuruma.png',
    price: 100,
    type: 'item',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ヒトデ（海）',
    imagePath: 'assets/images/item_sea_hitode.png',
    price: 100,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'イカリ（海）',
    imagePath: 'assets/images/item_sea_ikari.png',
    price: 100,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: '貝殻（海）',
    imagePath: 'assets/images/item_sea_kaigara.png',
    price: 100,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: '貝殻２（海）',
    imagePath: 'assets/images/item_sea_kaigara2.png',
    price: 100,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'サンゴ（海）',
    imagePath: 'assets/images/item_sea_sango.png',
    price: 100,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: '灯台（海）',
    imagePath: 'assets/images/item_sea_toudai.png',
    price: 200,
    type: 'item',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ベット',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/bet.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'いす１',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/isu1.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'いす２',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/isu2.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'いす３',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/isu3.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'キッチン',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/kicchin.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ランタン',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/rantan.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'しょっきだな',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/syokkidana.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'テーブル',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/table.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'たな',
    type: 'furniture',
    price: 150,
    imagePath: 'assets/images/house_interior_furniture/tana.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ベンチ（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_benchi.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ベット（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_bet.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'いす（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_isu.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'いす2（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_isu2.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'テーブル（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_table.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'たな（海）',
    type: 'furniture',
    price: 200,
    imagePath: 'assets/images/house_interior_furniture/sea_tana.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'バナナ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/banana.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ぶどう',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/budou.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'パイナップル',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/painappuru.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'リンゴ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/ringo.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'びん',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/bin.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ぎゅうにゅう',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/gyunyubin.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'コップ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/koppu.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'なべ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/nabe.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ボール',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/bool.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ほん',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/hon.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'かびん',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/kabin.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ぬいぐるみ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/kumanonuigurumi.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'もくば',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/mokuba.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'おもちゃ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/omotya1.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'タブレット',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/taburetto.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'たからばこ',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/takarabako.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'つみき',
    type: 'house_item',
    price: 50,
    imagePath: 'assets/images/house_interior_items/tumiki.png',
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'かがみ（海）',
    type: 'house_item',
    price: 100,
    imagePath: 'assets/images/house_interior_items/sea_kagami.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'クッション（海）',
    type: 'house_item',
    price: 100,
    imagePath: 'assets/images/house_interior_items/sea_kussyon.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'タツノオトシゴ（海）',
    type: 'house_item',
    price: 100,
    imagePath: 'assets/images/house_interior_items/sea_tatsunootoshigo.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ヨット（海）',
    type: 'house_item',
    price: 100,
    imagePath: 'assets/images/house_interior_items/sea_yotto.png',
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'いえ１',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_house1.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ２',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_house2.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ３',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_house3.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ４',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_house4.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ５',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_house5.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ６',
    type: 'building',
    price: 300,
    imagePath: 'assets/images/island/building_house6.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'いえ７',
    type: 'building',
    price: 300,
    imagePath: 'assets/images/island/building_house7.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'コンビニ',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_konbini.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'スーパー',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_su-pa-.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'びょういん',
    type: 'building',
    price: 300,
    imagePath: 'assets/images/island/building_byoin.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'けいさつしょ',
    type: 'building',
    price: 300,
    imagePath: 'assets/images/island/building_keisatsu.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'こうえん１',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_kouen1.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'こうえん２',
    type: 'building',
    price: 150,
    imagePath: 'assets/images/island/building_kouen2.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'おしろ',
    type: 'building',
    price: 1000,
    imagePath: 'assets/images/island/building_oshiro.png',
    requiredLevel: 10,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'くるま（しま）',
    type: 'vehicle',
    price: 150,
    imagePath: 'assets/images/island/vehicle_kuruma.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'タクシー（しま）',
    type: 'vehicle',
    price: 150,
    imagePath: 'assets/images/island/vehicle_takushi-.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'バス（しま）',
    type: 'vehicle',
    price: 200,
    imagePath: 'assets/images/island/vehicle_bus.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'ヘリコプター（しま）',
    type: 'vehicle',
    price: 150,
    imagePath: 'assets/images/island/vehicle_herikoputa-.png',
    requiredLevel: 5,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'ひこうせん１（しま）',
    type: 'vehicle',
    price: 500,
    imagePath: 'assets/images/island/vehicle_hikousen1.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'ひこうせん２（しま）',
    type: 'vehicle',
    price: 500,
    imagePath: 'assets/images/island/vehicle_hikousen2.png',
    requiredLevel: 8,
    isIslandOnly: true,
  ),
  ShopItem(
    name: 'びん（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_bin.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'イカリ（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_ikari.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'かいがら（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_kaigara.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'こんぶ１（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_konbu1.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'こんぶ２（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_konbu2.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さんご１（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_sango1.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さんご２（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_sango2.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'たからばこ（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_takarabako.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'トライデント（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_toraidento.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'つぼ（うみ）',
    type: 'sea_item',
    price: 100,
    imagePath: 'assets/images/sea/item_tubo.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'せんすいかん（うみ）',
    type: 'sea_item',
    price: 500,
    imagePath: 'assets/images/sea/item_sensuikan.png',
    requiredLevel: 15,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'ちんぼつせん（うみ）',
    type: 'sea_item',
    price: 500,
    imagePath: 'assets/images/sea/item_tinbotsusen.png',
    requiredLevel: 15,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'ふぐ',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_fugu.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'ひとで',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_hitode.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'いか',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_ika.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'イルカ',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_iruka.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'かめ',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_kame.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'かに',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_kani.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'クラゲ',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_kurage.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さかな１',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_sakana1.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さかな２',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_sakana2.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さかな３',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_sakana3.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'さかな４',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_sakana4.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'サメ１',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_same1.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'サメ２',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_same2.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'たつのおとしご',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_tatsunootoshigo.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'ヤドカリ',
    type: 'living',
    price: 200,
    imagePath: 'assets/images/sea/living_yadokari.png',
    requiredLevel: 10,
    isSeaOnly: true,
  ),
  ShopItem(
    name: 'ふうせん１（そら）',
    type: 'sky_item',
    price: 100,
    imagePath: 'assets/images/sky/item_huusen1.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ふうせん２（そら）',
    type: 'sky_item',
    price: 100,
    imagePath: 'assets/images/sky/item_huusen2.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ふうせん３（そら）',
    type: 'sky_item',
    price: 100,
    imagePath: 'assets/images/sky/item_huusen3.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ふうせん４（そら）',
    type: 'sky_item',
    price: 100,
    imagePath: 'assets/images/sky/item_huusen4.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'くも（そら）',
    type: 'sky_item',
    price: 100,
    imagePath: 'assets/images/sky/item_kumo.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ヘリコプター（そら）',
    type: 'sky_item',
    price: 200,
    imagePath: 'assets/images/sky/item_herikoputa-.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ひこうき１（そら）',
    type: 'sky_item',
    price: 200,
    imagePath: 'assets/images/sky/item_hikouki1.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ひこうき２（そら）',
    type: 'sky_item',
    price: 200,
    imagePath: 'assets/images/sky/item_hikouki2.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ひこうき３（そら）',
    type: 'sky_item',
    price: 400,
    imagePath: 'assets/images/sky/item_hikouki3.png',
    requiredLevel: 18,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ひこうき４（そら）',
    type: 'sky_item',
    price: 400,
    imagePath: 'assets/images/sky/item_hikouki4.png',
    requiredLevel: 18,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ひこうせん（そら）',
    type: 'sky_item',
    price: 200,
    imagePath: 'assets/images/sky/item_hikousen.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ききゅう（そら）',
    type: 'sky_item',
    price: 200,
    imagePath: 'assets/images/sky/item_kikyuu.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'せんとうき１（そら）',
    type: 'sky_item',
    price: 300,
    imagePath: 'assets/images/sky/item_sentouki1.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'せんとうき２（そら）',
    type: 'sky_item',
    price: 500,
    imagePath: 'assets/images/sky/item_sentouki2.png',
    requiredLevel: 18,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'はち（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_hati.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'フクロウ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_hukurou.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'コウモリ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_koumori.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'モモンガ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_momonga.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'オウム（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_oumu.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'スズメ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_suzume.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'てんとうむし（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_tentoumushi.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'とんぼ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_tonbo.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ツル（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_tsuru.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ちょうちょ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_tyoutyo.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'ワシ（そら）',
    type: 'sky_living',
    price: 200,
    imagePath: 'assets/images/sky/living_washi.png',
    requiredLevel: 15,
    isSkyOnly: true,
  ),
  ShopItem(
    name: 'いんせき１（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_inseki1.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'いんせき２（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_inseki2.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'いんせき３（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_inseki3.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'えいせい１（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_jinkoueisei1.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'えいせい２（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_jinkoueisei2.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'わくせい１（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_wakusei1.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'わくせい２（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_wakusei2.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'わくせい３（宇宙）',
    type: 'space_item',
    price: 150,
    imagePath: 'assets/images/space/item_wakusei3.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'ロケット（宇宙）',
    type: 'space_item',
    price: 300,
    imagePath: 'assets/images/space/item_roketto.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'シャトル（宇宙）',
    type: 'space_item',
    price: 300,
    imagePath: 'assets/images/space/item_supe-susyatoru.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'ユーフォー（宇宙）',
    type: 'space_item',
    price: 300,
    imagePath: 'assets/images/space/item_ufo.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん１（宇宙）',
    type: 'space_living',
    price: 300,
    imagePath: 'assets/images/space/living_utyujin1.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん２（宇宙）',
    type: 'space_living',
    price: 300,
    imagePath: 'assets/images/space/living_utyujin2.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん３（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin3.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん４（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin4.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん５（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin5.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん６（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin6.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん７（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin7.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん８（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin8.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'うちゅうじん９（宇宙）',
    type: 'space_living',
    price: 200,
    imagePath: 'assets/images/space/living_utyujin9.png',
    requiredLevel: 20,
    isSpaceOnly: true,
  ),
  ShopItem(
    name: 'いつものかお',
    imagePath: 'assets/images/face/face_default.png',
    type: 'face',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: '頑張るかお',
    imagePath: 'assets/images/face/face_ganbaru.png',
    type: 'face',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: '困ったかお',
    imagePath: 'assets/images/face/face_komatta.png',
    type: 'face',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ウインクしているかお',
    imagePath: 'assets/images/face/face_uinku.png',
    type: 'face',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'にやけがお',
    imagePath: 'assets/images/face/face_niyake.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '大喜びのかお',
    imagePath: 'assets/images/face/face_ooyorokobi.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '青い瞳の女の子のかお',
    imagePath: 'assets/images/face/face_girl_blue.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '緑の瞳の女の子のかお',
    imagePath: 'assets/images/face/face_girl_green.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '青い瞳の男の子のかお',
    imagePath: 'assets/images/face/face_boy_blue.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '緑の瞳の男の子のかお',
    imagePath: 'assets/images/face/face_boy_green.png',
    type: 'face',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '赤い瞳の女の子のかお',
    imagePath: 'assets/images/face/face_girl_red.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '紫の瞳の女の子のかお',
    imagePath: 'assets/images/face/face_girl_murasaki.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '黒い瞳の女の子のかお',
    imagePath: 'assets/images/face/face_girl_black.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '赤い瞳の男の子のかお',
    imagePath: 'assets/images/face/face_boy_red.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '紫の瞳の男の子のかお',
    imagePath: 'assets/images/face/face_boy_murasaki.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '黒い瞳の男の子のかお',
    imagePath: 'assets/images/face/face_boy_black.png',
    type: 'face',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'シーブルーの瞳のかお（海）',
    imagePath: 'assets/images/face/face_sea_blue.png',
    type: 'face',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '灰色の瞳のかお（海）',
    imagePath: 'assets/images/face/face_sea_haiiro.png',
    type: 'face',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '水色の瞳のかお（海）',
    imagePath: 'assets/images/face/face_sea_mizuiro.png',
    type: 'face',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '赤い瞳のかお（海）',
    imagePath: 'assets/images/face/face_sea_red.png',
    type: 'face',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'いつものかみがた',
    imagePath: 'assets/images/hair/hair_default.png',
    type: 'hair',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ポニーテールかみがた',
    imagePath: 'assets/images/hair/hair_poni-te-ru.png',
    type: 'hair',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'おとこのこのかみがた',
    imagePath: 'assets/images/hair/hair_boy_default.png',
    type: 'hair',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'アシメかみがた',
    imagePath: 'assets/images/hair/hair_ashime.png',
    type: 'hair',
    price: 0,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ピンクツインテールかみがた',
    imagePath: 'assets/images/hair/hair_pink_tuinte-ru.png',
    type: 'hair',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ふんわりかみがた',
    imagePath: 'assets/images/hair/hair_hunwari.png',
    type: 'hair',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'オレンジアフロかみがた',
    imagePath: 'assets/images/hair/hair_orenge_afuro.png',
    type: 'hair',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '茶色ボッチャマかみがた',
    imagePath: 'assets/images/hair/hair_buraun_bottyan.png',
    type: 'hair',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '坊主頭のかみがた',
    imagePath: 'assets/images/hair/hair_bouzu.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'シルバーザンバラのかみがた',
    imagePath: 'assets/images/hair/hair_siruba-_zanbara.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '刈り上げのかみがた',
    imagePath: 'assets/images/hair/hair_kariage.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おとこのレゲエのかみがた',
    imagePath: 'assets/images/hair/hair_boy_regee.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '緑の花のかみがた',
    imagePath: 'assets/images/hair/hair_green_hana.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '紫のロングヘア',
    imagePath: 'assets/images/hair/hair_murasaki_long.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おんなのレゲエのかみがた',
    imagePath: 'assets/images/hair/hair_girl_regee.png',
    type: 'hair',
    price: 100,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'お団子ヘア（海）',
    imagePath: 'assets/images/hair/hair_sea_dango.png',
    type: 'hair',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ポニーテールヘア（海）',
    imagePath: 'assets/images/hair/hair_sea_poni-te-ru.png',
    type: 'hair',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ビーチクロップ（海）',
    imagePath: 'assets/images/hair/hair_sea_bi-tikuroppu.png',
    type: 'hair',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ジェリサイト（海）',
    imagePath: 'assets/images/hair/hair_sea_jerusaido.png',
    type: 'hair',
    price: 150,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '青いティアラ',
    imagePath: 'assets/images/headgear/headgear_blue_thiara.png',
    type: 'headgear',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ピンクティアラ',
    imagePath: 'assets/images/headgear/headgear_pink_thiara.png',
    type: 'headgear',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '赤いティアラ',
    imagePath: 'assets/images/headgear/headgear_red_thiara.png',
    type: 'headgear',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'くまのみみ',
    imagePath: 'assets/images/headgear/headgear_kuma.png',
    type: 'headgear',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'おうかん',
    imagePath: 'assets/images/headgear/headgear_oukan.png',
    type: 'headgear',
    price: 50,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'ヘッドバンド（海）',
    imagePath: 'assets/images/headgear/headgear_sea_heaband.png',
    type: 'headgear',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'ヘッドバンド2（海）',
    imagePath: 'assets/images/headgear/headgear_sea_heaband2.png',
    type: 'headgear',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '海賊のハット（海）',
    imagePath: 'assets/images/headgear/headgear_sea_kaizoku.png',
    type: 'headgear',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'マリン帽（海）',
    imagePath: 'assets/images/headgear/headgear_sea_mari-n.png',
    type: 'headgear',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'はなのバッジ',
    imagePath: 'assets/images/accessory/accessory_hana.png',
    type: 'accessory',
    price: 50,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'りぼんのバッジ',
    imagePath: 'assets/images/accessory/accessory_ribon.png',
    type: 'accessory',
    price: 50,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'ほしのバッジ',
    imagePath: 'assets/images/accessory/accessory_hoshi.png',
    type: 'accessory',
    price: 50,
    requiredLevel: 1,
  ),
  ShopItem(
    name: '剣のバッジ',
    imagePath: 'assets/images/accessory/accessory_ken.png',
    type: 'accessory',
    price: 50,
    requiredLevel: 1,
  ),
  ShopItem(
    name: 'くまのぬいぐるみ',
    imagePath: 'assets/images/accessory/accessory_kumanonuigurumi.png',
    type: 'accessory',
    price: 70,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'まほうのステッキ',
    imagePath: 'assets/images/accessory/accessory_mahou_stekki.png',
    type: 'accessory',
    price: 70,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '冒険の本',
    imagePath: 'assets/images/accessory/accessory_bouken_hon.png',
    type: 'accessory',
    price: 70,
    requiredLevel: 5,
  ),
  ShopItem(
    name: '時計のバッジ',
    imagePath: 'assets/images/accessory/accessory_tokei.png',
    type: 'accessory',
    price: 70,
    requiredLevel: 5,
  ),
  ShopItem(
    name: 'いかりのバッジ（海）',
    imagePath: 'assets/images/accessory/accessory_sea_ikari.png',
    type: 'accessory',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: '貝殻の指輪（海）',
    imagePath: 'assets/images/accessory/accessory_sea_kaigaranoyubiwa.png',
    type: 'accessory',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'サンゴの指輪（海）',
    imagePath: 'assets/images/accessory/accessory_sea_sangonoyubiwa.png',
    type: 'accessory',
    price: 100,
    requiredLevel: 10,
  ),
  ShopItem(
    name: 'タツノオトシゴのバッジ（海）',
    imagePath: 'assets/images/accessory/accessory_sea_tatsunootoshigo.png',
    type: 'accessory',
    price: 100,
    requiredLevel: 10,
  ),
];
